// frontend-vue/src/components/AddPost.vue
<template>
  <h3>Add Post</h3>
  <form @submit.prevent="handleAdd">
    <label for="title">Title</label>
    <input type="text" name="title" id="title" v-model="post.title">
    <label for="image">Image</label>
    <input type="text" name="image" id="image" v-model="post.image">
    <label for="description">Description</label>
    <input type="text" name="description" id="description" v-model="post.description">
    <label for="publishedDate">PublishedDate</label>
    <input type="date" name="publishedDate" id="publishedDate" v-model="post.publishedDate">
    <input type="submit" value="Add Post">
  </form>
</template>

<script setup>
import axios from 'axios';
import { reactive } from 'vue';
import { useToast } from 'vue-toastification';
import { useRouter } from 'vue-router';

const post = reactive({
  title: '',
  image: '',
  description: '',
  publishedDate: ''
})

const toast = useToast()
const route = useRouter()

const handleAdd = async () => {
  try {
    const p = {
      title: post.title,
      image: post.image,
      description: post.description,
      publishedDate: post.publishedDate
    }
    await axios.post('/api/posts', p)
    toast.success('Add Post Successfully')
    route.push('/posts')
  } catch (error) {
    toast.error(error.message)
  }
}


</script>

// frontend-react/src/components/AddPost.jsx
import axios from "axios";
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";

const AddPost = () => {
  const [post, setPost] = useState({
    title: "",
    image: "",
    description: "",
    publishedDate: "",
  });
  const naviate = useNavigate();
  const handleChange = (e) => {
    setPost({ ...post, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    addPost(post);
  };

  const addPost = async (post) => {
    try {
      await axios.post("/api/posts", post);
      toast.success("Added Post Successfully");
      naviate("/posts");
    } catch (error) {
      toast.error("Failed to Add Post");
    }
  };

  return (
    <>
      <h3>Add Post</h3>
      <form onSubmit={handleSubmit}>
        <label htmlFor="title">Title</label>
        <input type="text" name="title" id="title" onChange={handleChange} />
        <label htmlFor="image">Image</label>
        <input type="text" name="image" id="image" onChange={handleChange} />
        <label htmlFor="description">Description</label>
        <input
          type="text"
          name="description"
          id="description"
          onChange={handleChange}
        />
        <label htmlFor="publishedDate">PublishedDate</label>
        <input
          type="date"
          name="publishedDate"
          id="publishedDate"
          onChange={handleChange}
        />
        <input type="submit" value="Add Post" />
      </form>
    </>
  );
};

export default AddPost;
