// frontend-vue/src/components/Header.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router';

</script>

<template>
  <div class="header">
    <h2>Blog Name</h2>
  </div>
  <ul>
    <li>
      <RouterLink to="/">Home</RouterLink>
    </li>
    <li>
      <RouterLink to="/posts">Posts</RouterLink>
    </li>
    <li>
      <RouterLink to="/add">Add Post</RouterLink>
    </li>
  </ul>
</template>

// frontend-react/src/components/Header.jsx
import React from "react";
import { Link } from "react-router-dom";

const Header = () => {
  return (
    <>
      <div className="header">
        <h2>Blog Name</h2>
      </div>
      <ul>
        <li>
          <Link to="/">Home</Link>
        </li>
        <li>
          <Link to="/posts">Post</Link>
        </li>
        <li>
          <Link to="/add">Add Post</Link>
        </li>
      </ul>
    </>
  );
};
export default Header;
