// frontend-vue/src/components/UpdatePost.vue
<template>
  <h3>Update Post</h3>
  <form @submit.prevent="handleUpdate">
    <label for="title">Title</label>
    <input type="text" name="title" id="title" v-model="post.title">
    <label for="image">Image</label>
    <input type="text" name="image" id="image" v-model="post.image">
    <label for="description">Description</label>
    <input type="text" name="description" id="description" v-model="post.description">
    <label for="publishedDate">PublishedDate</label>
    <input type="date" name="publishedDate" id="publishedDate" v-model="post.publishedDate">
    <input type="submit" value="Update Post">
  </form>
</template>

<script setup>
import axios from 'axios';
import { onMounted, reactive } from 'vue';
import { useToast } from 'vue-toastification';
import { useRoute, useRouter } from 'vue-router';

const post = reactive({
  title: '',
  image: '',
  description: '',
  publishedDate: ''
})

const toast = useToast()
const router = useRouter()
const route = useRoute()
const postId = route.params.id

// handle update
const handleUpdate = async () => {
  try {
    const p = {
      title: post.title,
      image: post.image,
      description: post.description,
      publishedDate: post.publishedDate
    }
    await axios.put(`/api/posts/${postId}`, p)
    toast.success('Update Post Successfully')
    router.push('/posts')
  } catch (error) {
    toast.error(error.message)
  }
}

onMounted(async () => {
  try {
    const response = await axios.get(`/api/posts/${postId}`)
    const { title, image, description, publishedDate } = response.data
    post.title = title,
      post.image = image,
      post.description = description,
      post.publishedDate = publishedDate
  } catch (error) {
    toast.error(error.message)
  }
})
</script>

// frontend-react/src/components/UpdatePost.jsx
import axios from "axios";
import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "react-toastify";

const UpdatePost = () => {
  const [post, setPost] = useState({
    title: "",
    image: "",
    description: "",
    publishedDate: "",
  });

  const naviate = useNavigate();
  const { id } = useParams();

  const handleChange = (e) => {
    setPost({ ...post, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    updatePost(post);
  };

  const updatePost = async (post) => {
    try {
      await axios.put(`/api/posts/${id}`, post);
      toast.success("Updated Post Successfully");
      naviate("/posts");
    } catch (error) {
      toast.error("Failed to Add Post");
    }
  };

  useEffect(() => {
    const getPost = async () => {
      const { data } = await axios.get(`/api/posts/${id}`);
      setPost(data);
    };
    getPost();
  }, [id]);

  return (
    <>
      <h3>Add Post</h3>
      <form onSubmit={handleSubmit}>
        <label htmlFor="title">Title</label>
        <input
          type="text"
          name="title"
          id="title"
          value={post.title}
          onChange={handleChange}
        />
        <label htmlFor="image">Image</label>
        <input
          type="text"
          name="image"
          id="image"
          value={post.image}
          onChange={handleChange}
        />
        <label htmlFor="description">Description</label>
        <input
          type="text"
          name="description"
          id="description"
          value={post.description}
          onChange={handleChange}
        />
        <label htmlFor="publishedDate">PublishedDate</label>
        <input
          type="date"
          name="publishedDate"
          id="publishedDate"
          value={post.publishedDate}
          onChange={handleChange}
        />
        <input type="submit" value="Update Post" />
      </form>
    </>
  );
};

export default UpdatePost;
